### ISSUE TITLE
Doesn't work with minimap

### ISSUE THREAD

**Issue by michael-yx-wu** [justmoon/relative-numbers#17]
When the minimap is on the left, the relative-numbers make the minimap disappear. When in insert mode, the minimap appears again (probably because the plugin returns your line numbers to normal).

**Comment by pbdm** [comment]
have the same problem, doesn't sure it's a feature or an issue

**Comment by ckrailo** [comment]
as a workaround, turning off absolute mode in minimap fixes the problem for me

<img width="891" alt="screenshot 2016-08-23 03 00 22" src="https://cloud.githubusercontent.com/assets/51341/17888051/0dd05e12-68de-11e6-8545-116d033064ea.png">

**Comment by michael-yx-wu** [comment]
keeping absolute mode off seems to work for me

**Comment by justmoon** [comment]
Works for me, closing. I reckon something got fixed somewhere along the way.

**Comment by bennypowers** [comment]
fix for this: https://github.com/justmoon/relative-numbers/pull/54/files
