### ISSUE TITLE
Breaks vim ex-mode

### ISSUE THREAD

**Issue by jimcroft** [justmoon/relative-numbers#19]
Not sure if this is an issue with this package or https://atom.io/packages/ex-mode

When I have relative-numbers package installed and enabled ex-mode doesn't seem to work. Commands like `:` + `w` + `<cr>` to write the current file don't work, instead adding a new line to the `:` ex-mode command/prompt line.

**Comment by justmoon** [comment]
Just tested, works for me. LMK if this is still an issue.
