### ISSUE TITLE
Deprecated selector in `relative-numbers/styles/main.less`

### ISSUE THREAD

**Issue by samueljun** [justmoon/relative-numbers#24]
In `relative-numbers/styles/main.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .relative.current-line` => `atom-text-editor.editor .syntax--relative.current-line`

* `atom-text-editor::shadow .absolute` => `atom-text-editor.editor .syntax--absolute`

* `atom-text-editor::shadow .gutter[gutter-name='relative-numbers']` => `atom-text-editor.editor .gutter[gutter-name='relative-numbers']`

* `atom-text-editor.vim-mode.insert-mode::shadow .absolute,
atom-text-editor.vim-mode-plus.insert-mode::shadow .absolute` => `atom-text-editor.vim-mode.insert-mode.editor .syntax--absolute,
atom-text-editor.vim-mode-plus.insert-mode.editor .syntax--absolute`

* `atom-text-editor.vim-mode.insert-mode::shadow .relative,
atom-text-editor.vim-mode-plus.insert-mode::shadow .relative` => `atom-text-editor.vim-mode.insert-mode.editor .syntax--relative,
atom-text-editor.vim-mode-plus.insert-mode.editor .syntax--relative`

* `atom-text-editor::shadow .show-absolute .absolute` => `atom-text-editor.editor .show-absolute .syntax--absolute`

* `atom-text-editor::shadow .show-absolute .relative` => `atom-text-editor.editor .show-absolute .syntax--relative`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by everdimension** [comment]
Proposed a PR here: https://github.com/justmoon/relative-numbers/pull/27

**Comment by justmoon** [comment]
Should be fixed, thanks!
