### ISSUE TITLE
Relative number becomes absolute if line changes on save

### ISSUE THREAD

**Issue by lumio** [justmoon/relative-numbers#28]
When saving file, lines that get trimmed show the absolute line number.
![screen](https://cloud.githubusercontent.com/assets/914637/21981006/bd11ab54-dbe5-11e6-82cd-9b21d3927c00.gif)
Sorry for the slow gif... it takes some moments to see what I mean 😄

**Comment by justmoon** [comment]
Mmmh, the way this extension works is by updating the gutter after Atom modifies it. So it looks like this is a case where trimming a line doesn't emit any of the events that we listen to, but does reset that line's gutter.

Valid bug - I don't have time to work on it at the moment, but would accept a PR if anyone would like to give it a shot.

**Comment by justmoon** [comment]
No longer an issue I believe, please lmk if I'm wrong.
