### ISSUE TITLE
Wrong number

### ISSUE THREAD

**Issue by hnguyen94** [justmoon/relative-numbers#3]
If I'm using vim select line "ctrl + v" then it shows me the wrong line number.

![screen shot 2015-11-26 at 11 51 23](https://cloud.githubusercontent.com/assets/8395044/11421281/0d985e10-9434-11e5-9a75-401a35db9141.jpg)

**Comment by crshd** [comment]
This has nothing to do with vim-mode(-plus). Same happens when selecting lines using `Ctrl-L` in "normal" Atom.

**Comment by crshd** [comment]
A bit whacky, but it works.

**Comment by hnguyen94** [comment]
Thanks!
