### ISSUE TITLE
question about releasing forked version.

### ISSUE THREAD

**Issue by t9md** [justmoon/relative-numbers#32]
I have some new-feature idea to use with vim-mode-plus I'm maintaining.
And I want use relative-numbers with my PR #30, #31 merged.

Do you have any strong opinion for me to publish forked version of relative-numbers?

I will name it something like relative-number2.

Hope give me some feedback.

**Comment by mauricerkelly** [comment]
@t9md I would love to see a fork of this package released (suggest `relative-line-numbers`)? I love your Vim mode package, and I'd be much happier knowing an active participant in the Atom community was looking after this feature.

**Comment by justmoon** [comment]
Totally fine - this package is itself a fork of an unmaintained version!

**Comment by t9md** [comment]
OK, Thanks!
But I'm currently not using relative-number, so not likely at the moment.
