### ISSUE TITLE
Absolute Numbers Mismatch at Collapsed Functions

### ISSUE THREAD

**Issue by Semnodime** [justmoon/relative-numbers#33]
Im not sure whether this is a bug or a feature:
When activating relative numbers in a python file with collapsed functions, the current line value for "absolute line" displays correctly. Though when showing absolute numers by either entering vim insert mode or activating permanent absolute number view in the settings, the whole (collapsed) function counts as one line regardless of its size.

**Comment by justmoon** [comment]
Hmm, I don't use collapsed functions, so this may be a bug. What's the behavior if you don't have `relative-numbers` installed? Ideally, that's what we should match for absolute line numbers.

**Comment by Semnodime** [comment]
So without the relative numbers the number-bar looks like this:
(In all examples there is one / the same collapsed function)
![grafik](https://cloud.githubusercontent.com/assets/19511852/25956477/24398de8-366c-11e7-8437-95bd5d8a5d2b.png)
With relative numbers everything seems fine…
![grafik](https://cloud.githubusercontent.com/assets/19511852/25956543/4cf3098a-366c-11e7-94fe-20001fc978a4.png)
But once you activate vim-mode’s insert mode the following is happening:
![grafik](https://cloud.githubusercontent.com/assets/19511852/25956674/a8401422-366c-11e7-8b9f-de248db51063.png)
Now, the absolute number isn’t quite correct which can be irritating when debugging with absolute line numbers and without awareness of this behavior.
I expected picture 3 to show the same behavior as picture 1

**Comment by justmoon** [comment]
Gotcha, this is definitely a legitimate issue then. I won't have time to look at the causes myself anytime soon, but happy to accept a PR if anyone is reading this.
