### ISSUE TITLE
Additional artifact in gutter

### ISSUE THREAD

**Issue by efleming969** [justmoon/relative-numbers#34]
I don't know if this is related to the plugin, but a rogue number shows up in the gutter and it goes away if I disable the plugin.

See the 1 next to the closing curly brace.
<img width="763" alt="screen shot 2017-03-17 at 7 14 03 pm" src="https://cloud.githubusercontent.com/assets/27506/24067083/34171dbc-0b46-11e7-9a9c-7635843ead17.png">

**Comment by IgorGee** [comment]
I'm also having this issue.

**Comment by elclanrs** [comment]
Looks like there are two elements with the class `line-number` at that creates a conflict. I was able to fix this temporarily by overriding line 109 in [line-number-view.coffee](https://github.com/justmoon/relative-numbers/blob/master/lib/line-number-view.coffee#L109) to query a more specific selector:

```coffeescript
# lineNumberElements = @editorView.rootElement?.querySelectorAll('.line-number')
lineNumberElements = @editorView.rootElement?.querySelectorAll('.line-numbers .line-number')
```

**Comment by thancock20** [comment]
I came here for the same issue, and I can verify that the solution from @elclanrs worked for me as well.

**Comment by elclanrs** [comment]
@justmoon, if you think this is the right solution I can submit a PR. I just don't know the codebase enough to tell if there is a better way...

**Comment by fl0w** [comment]
Oh, I was going crazy, it came post an update and I thought it was a feature.

**Comment by fuddmain** [comment]
I had the same issue.  I assume everyone here updated to the latest linter-default-ui.  That's when it showed up for me.  Adding this to styles.less solved it:

  `.linter-cursor-line .relative { display: none !important;}`

Cheers.

**Comment by fuddmain** [comment]
Taking a real quick look, linter-ui-default is adding a gutter to the editor,  Then, either this package, or the code for the Atom gutter is inserting the line-number elements into any .gutter class.  So, the main gutter and the linter gutter get line-numbers.

Seems like @elclanrs is on the right track for a permanent solution.  This package can be more specific as to which gutter gets the relative-numbers.

**Comment by nwaywood** [comment]
Is it just me or does @fuddmain's solution not fix the problem in files with less than 10 lines (in insert mode)?

**Comment by fuddmain** [comment]
@nwaywood @despairblue 

Didn't show for me because I've done a bunch of gutter tweaking.  I rolled back a bunch of the tweaks and saw what you describe.  I had a min-width set for the gutter which hid the problem.

Taking another quick look, I think this is the best solution:

`      .linter-row {
        .absolute, .relative { display:none; }
      }
`
YMMV

Cheers

**Comment by nwaywood** [comment]
Thanks @fuddmain 😄 

that didn't exactly fix the problem for me, but when I added the `!important` flag it did.

` .linter-row { .absolute, .relative { display:none !important; } }`
