### ISSUE TITLE
Bug with generic selector

### ISSUE THREAD

**Issue by nwaywood** [justmoon/relative-numbers#36]
Please see [this issue](https://github.com/t9md/atom-vim-mode-plus/issues/706)

Essentially, the generic selector that is defined [here](https://github.com/justmoon/relative-numbers/blob/master/lib/line-number-view.coffee#L109) (`@editorView.rootElement?.querySelectorAll('.line-number')`) clashes with the [linter-ui-default](https://atom.io/packages/linter-ui-default) package that also uses the `.line-number` class.

The selector needs to be made more specific to only target the `line-numbers` class in the gutter

**Comment by despairblue** [comment]
Have a look at #34, this is a duplicate of that one.

**Comment by nwaywood** [comment]
Ah sorry I must of missed this issue, closing
