### ISSUE TITLE
HTMLElement.rootElement is deprecated. - Stable

### ISSUE THREAD

**Issue by heftyfunseeker** [justmoon/relative-numbers#43]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `rootElement` and access
the editor contents directly instead.
```
HTMLElement.rootElement (C:\Users\Nicco\AppData\Local\atom\app-1.19.0-beta7\resources\app\src\text-editor-element.js:23:10)
LineNumberView._updateSync (C:\Users\Nicco\.atom\packages\relative-numbers\lib\line-number-view.coffee:101:50)
_updateSync (C:\Users\Nicco\.atom\packages\relative-numbers\lib\line-number-view.coffee:3:59)
<unknown> (C:\Users\Nicco\.atom\packages\relative-numbers\lib\line-number-view.coffee:83:26)
ViewRegistry.performDocumentUpdate (<embedded>:20098:15)
<unknown> (<embedded>:19914:65)
```

**Comment by linjialiang** [comment]
![default](https://user-images.githubusercontent.com/8848263/29307987-99fe170a-81d6-11e7-8a8e-0ebe52c82445.png)

**Comment by linjialiang** [comment]
Is this plug-in still in maintenance

**Comment by fenec** [comment]
the fix was merged to master, but the release is yet to come. you can apply it on your own for now:
https://github.com/justmoon/relative-numbers/pull/40/files

**Comment by linjialiang** [comment]
hy not release?

**Comment by linjialiang** [comment]
Thank you. The original question has been settled!
But why isn't there a new version?

**Comment by binarious** [comment]
@justmoon A new version would help us 🙂.

**Comment by mike3run** [comment]
@binarious @linjialiang while the author figures things out i've published the fix in a new package

https://atom.io/packages/relative-numbers-plus

**Comment by Aventura5** [comment]
@mike3run It would be helpful if you explained what the difference was in the readme for your relative-numbers-plus package. I just installed relative-numbers and saw yours in the list but had no idea what the difference was.

**Comment by mike3run** [comment]
@Aventura5 i dun goofed, lol what I did is grab the PR request the are talking about and published that, but it didn't work, i guess it has other breaking changes we are not aware of so for now you're better off applying this manually on the normal package installation:

https://github.com/justmoon/relative-numbers/pull/40/files

**Comment by mauricerkelly** [comment]
Hey @justmoon - could you please produce a new release for this? If you haven't got the bandwidth to do it, maybe you could ask for a volunteer to help maintain the package?

**Comment by dannyfritz** [comment]
http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#transferring-ownership

**Comment by basicBrogrammer** [comment]
Soooooo new version ?

**Comment by mike3run** [comment]
lol its clearly not gonna happen (specially now on December...) you're better off either:

- Doing the hot fix locally 2 lines of code: https://github.com/justmoon/relative-numbers/pull/40/files

- Doing a fork and now maintaining it yourself

**Comment by justmoon** [comment]
Upgrade to 0.8.1. Apologies for the delay, I thought I had bumped the version but apparently not.
