### ISSUE TITLE
atom 1.19.0

### ISSUE THREAD

**Issue by linjialiang** [justmoon/relative-numbers#45]
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using rootElement and access the editor contents directly instead.
Report Issue
HTMLElement.rootElement - C:\Users\kc_em\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-element.js:23:10
LineNumberView._updateSync - C:\Users\kc_em\.atom\packages\relative-numbers\lib\line-number-view.coffee:101:50
_updateSync - C:\Users\kc_em\.atom\packages\relative-numbers\lib\line-number-view.coffee:3:59
<unknown> - C:\Users\kc_em\.atom\packages\relative-numbers\lib\line-number-view.coffee:83:26
ViewRegistry.performDocumentUpdate - <embedded>:20098:15
<unknown> - <embedded>:19914:65

**Comment by mike3run** [comment]
https://atom.io/packages/relative-numbers-plus

**Comment by justmoon** [comment]
Fixed in 0.8.1.
