### ISSUE TITLE
Off-by-one with vim-mode-plus line-wise visual

### ISSUE THREAD

**Issue by NeoRaider** [justmoon/relative-numbers#51]
Steps to reproduce:

* Use vim-mode-plus
* Press `V` to enter line-wise visual selection
* Press "up" key (the issue only occurs when selecting upwards)

The line numbers are now shown relative to one line above the cursor.

Versions: Atom 1.21.1, vim-mode-plus 1.11.2, relative-numbers 0.8.0

**Comment by justmoon** [comment]
Thanks for reporting! There is actually an issue about this already: #21.
